require('plugins')
require('keybindings')
require('options')
require('nvim-tree-config')
require('lualine-config')
require('bufferline-config')
require('treesitter-config')
require('autopairs-config')
require('telescope-config')
require('whichkey-config')
require('colorizer-config')
require('dashboard-config')
require('spectre-config')
require('lsp')
require('plugins/material')
require('blankline-config')
-- vim.g.material_style = 'deep ocean'
vim.cmd('colorscheme rose-pine')
